name: PlayerShop
version: 1.5.0
author: GABRYCA
main: it.gabryca.playershop.Main
website: https://www.onlyplay.tk
commands:
  shoplogo:
    description: Change the block logo
    usage: /<command> <Block_ID> <shop_number>
  shops:
    description: Open a GUI with a list of shops
    usage: /<command>
  Playershop:
    description: Show all commands
    usage: /<command>
